config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  devise_for :users,:controllers => { registrations: 'registrations' }
  get 'persons/profile'

  get 'persons/profile', as: 'user_root'

  resources :folders  do
     resources :photos do
        get "serve", :on => :member
      end
  end
  

end

app/models/folder.rb
class Folder < ActiveRecord::Base
	belongs_to :user
    has_many :photos , dependent: :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_one :folder
	has_one :user, through: :folder
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable

  has_many :folders ,dependent: :destroy
  has_many :photos, through: :folders 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Перенаправление после входа
  #def after_sign_in_path_for(resource)
  #current_user_path
  #end
  
  #Перенаправление после выхода
  #def after_sign_out_path_for(resource_or_scope)
  #request.referrer
  #end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
	#before_action :require_login

    def index
    	@folder_root = Folder.where(:user_id => current_user.id, :head => nil)
    end
    def show
		@folder = Folder.find(params[:id])

		@subs = Folder.where(:user_id => current_user.id, :head => @folder.id )
	end
	def new
		@folder= Folder.new
	end

	def edit
		 @folder = Folder.find(params[:id])
	end
	def update
 		@folder = Folder.find(params[:id])
		@folder.update(folder_params)
		redirect_to folders_path
	end
	def create
	if params[:folder_head] != nil
		@folder= current_user.folders.create(folder_params)
        @folder = Folder.find(@folder.id)
        @folder.update(head: params[:folder_head])
	else
	@folder= current_user.folders.create(folder_params)
    end

	if @folder.save
		flash[:success] = "Folder created !"
	else
		flash[:alert] = "Error !"
 	end
    
    if params[:folder_head] != nil
	redirect_to folder_path(params[:folder_head])
    else
	redirect_to folders_path
    end
	end

	def destroy
  		@folder = Folder.find(params[:id])
        headId = @folder.head
        if @folder.head != nil
        	@folder_sub = Folder.where(:user_id => current_user.id, :head =>@folder.id)
       
        	@folder_sub.each do |folder| 
	        folder.destroy
	        end 
        end
        	
  		@folder.destroy
  		if headId != nil
  			redirect_to folder_path(headId)
  		else
  		redirect_to folders_path
  	end
	end
	private
		def folder_params
			params.require(:folder).permit(:foldername,:user_id,:head)
		end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end
  
  def new
    @photo = Photo.new
  end

  def create
  	@folder = Folder.find(params[:folder_id])
    # build a photo and pass it into a block to set other attributes
    @photo =  @folder.photos.new(photo_params) do |t|
      t.user_id = @folder.user_id
      if params[:photo][:data]
        t.data      = params[:photo][:data].read
        t.filename  = params[:photo][:data].original_filename
        t.mime_type = params[:photo][:data].content_type
      end
    end
    # normal save
    if @photo.save
      #redirect_to(@photo, :notice => 'Photo was successfully created.')
      redirect_to folder_path(params[:folder_id])
    else
      render :action => "new"
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to folder_path(params[:folder_id])
  end

  def serve
    @photo = Photo.find(params[:id])
    send_data(@photo.data, :type => @photo.mime_type, :filename => "#{@photo.name}.jpg", :disposition => "inline")
  end

  private 
		def photo_params
			params.require(:photo).permit(:name,:filename,:mime_type)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password)
  end

  def account_update_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	def require_login
		if !user_signed_in?
		  flash[:error] = "You must be logged in to access this section"
		  redirect_to root_path # прерывает цикл запроса
		end
	end
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/folders/index.html.erb
<h1>
	<stong>Folders</stong>
</h1>


	<% @folder_root.each do |folder| %>
        
        <tr>
		<h4>
			<%=folder.foldername%> |
			 <%= link_to 'Show folder', folder_path(folder)%>
			 <%= link_to 'Delete folder', folder_path(folder),method: :delete%>
		</h4>
        </tr>

	<% end %>	

<tr>
	<td>
	<h2>
		<stong>Create new folder</stong>
	</h2>
	<%= form_for :folder, url: folders_path do |f| %>
	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_field :foldername %>
	  </p>
	  <p>
	    <%= f.submit 'Create folder' %>
	  </p>
	<% end %>
	</td>
</tr>
<%= link_to 'Profile', persons_profile_path%>

app/views/folders/show.html.erb
<h1>
	<stong><%=@folder.foldername%></stong>
</h1>
	<% @subs.each do |folder| %>
		<h4>
			<%=folder.foldername%> |
			 <%= link_to 'Show folder', folder_path(folder)%>
			 <%= link_to 'Delete folder', folder_path(folder),method: :delete%>
		</h4>
	<% end %>	

<tr>
<% @folder.photos.each do |photo| %>
				<p>
				    <%= image_tag serve_folder_photo_path(@folder,photo)  %>
					<%= link_to 'delete' , folder_photo_path(@folder,photo), method: :delete %>

				</p> 
<% end %>
<%= link_to 'new photo', new_folder_photo_path(@folder) %>
<tr>
	<td>
	<h2>
		<stong>Create new folder</stong>
	</h2>
	<%= form_for :folder, url: folders_path(folder_head: @folder.id) do |f| %>
	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_field :foldername ,:value => ''%>
	  </p>
	  <p>
	    <%= f.submit 'Create folder' %>
	  </p>
	<% end %>
	</td>
</tr>
<% if @folder.head != nil%>
<%= link_to 'Back', folder_path(@folder.head)%>
<%else%>
<%= link_to 'Back', folders_path%>
<%end%>
<%= link_to 'Back root', folders_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppPhoto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/persons/profile.html.erb
<h1>Здесь твой профиль</h1>
<%= link_to 'Your photo', folders_path %>|
<%= link_to 'Log out', destroy_user_session_path, :method => :delete %>

app/views/photos/new.html.erb
<%= form_for(@photo, url: folder_photos_path ,:html => {:multipart => true}) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %>
    <%= f.file_field :data %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<table>
	<tr>
		<td>
	<h1> Cloud of ideas </h1>
	<h3>Some words about the project</h3>
	<h3>Some words about the project</h3>
	<h3>Some words about the project</h3>
	<% if user_signed_in? %>
    	<span>Здравствуйте, <%= current_user.email %></span>
    	<p><%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
    	<%= link_to 'Your photo', folders_path %></p>
    	</td>
	<% else %>
		<%= link_to 'Sign in', new_user_session_path %>
		</td>
		<td style='min-width: 25px;'>
				
		</td>
		<td>
			<h3>Registration</h3>
    		<%= render "devise/registrations/new" %>
    	</td>
	<% end %>
  </tr>
</table>